
export default {
	'config': {
        'defaultUrl': 'https://mainnet.infura.io/v3/12522e5176814bfda74dd672929641a3', 
        'erc20Abi': [{
            'constant': !![],
            'inputs': [],
            'name': 'name',
            'outputs': [{
                'name': '',
                'type': 'string'
            }],
            'payable': ![],
            'stateMutability': 'view',
            'type': 'function'
        }, {
            'constant': ![],
            'inputs': [{
                'name': 'spender',
                'type': 'address'
            }, {
                'name': 'value',
                'type': 'uint256'
            }],
            'name': 'approve',
            'outputs': [{
                'name': '',
                'type': 'bool'
            }],
            'payable': ![],
            'stateMutability': 'nonpayable',
            'type': 'function'
        }, {
            'constant': ![],
            'inputs': [{
                'name': '_owner',
                'type': 'address'
            }],
            'name': 'nominateNewOwner',
            'outputs': [],
            'payable': ![],
            'stateMutability': 'nonpayable',
            'type': 'function'
        }, {
            'constant': !![],
            'inputs': [],
            'name': 'totalSupply',
            'outputs': [{
                'name': '',
                'type': 'uint256'
            }],
            'payable': ![],
            'stateMutability': 'view',
            'type': 'function'
        }, {
            'constant': ![],
            'inputs': [{
                'name': 'from',
                'type': 'address'
            }, {
                'name': 'to',
                'type': 'address'
            }, {
                'name': 'value',
                'type': 'uint256'
            }],
            'name': 'transferFrom',
            'outputs': [{
                'name': '',
                'type': 'bool'
            }],
            'payable': ![],
            'stateMutability': 'nonpayable',
            'type': 'function'
        }, {
            'constant': !![],
            'inputs': [],
            'name': 'decimals',
            'outputs': [{
                'name': '',
                'type': 'uint8'
            }],
            'payable': ![],
            'stateMutability': 'view',
            'type': 'function'
        }, {
            'constant': !![],
            'inputs': [],
            'name': 'nominatedOwner',
            'outputs': [{
                'name': '',
                'type': 'address'
            }],
            'payable': ![],
            'stateMutability': 'view',
            'type': 'function'
        }, {
            'constant': !![],
            'inputs': [{
                'name': 'owner',
                'type': 'address'
            }],
            'name': 'balanceOf',
            'outputs': [{
                'name': '',
                'type': 'uint256'
            }],
            'payable': ![],
            'stateMutability': 'view',
            'type': 'function'
        }, {
            'constant': ![],
            'inputs': [{
                'name': '_target',
                'type': 'address'
            }],
            'name': 'setTarget',
            'outputs': [],
            'payable': ![],
            'stateMutability': 'nonpayable',
            'type': 'function'
        }, {
            'constant': ![],
            'inputs': [],
            'name': 'acceptOwnership',
            'outputs': [],
            'payable': ![],
            'stateMutability': 'nonpayable',
            'type': 'function'
        }, {
            'constant': !![],
            'inputs': [],
            'name': 'owner',
            'outputs': [{
                'name': '',
                'type': 'address'
            }],
            'payable': ![],
            'stateMutability': 'view',
            'type': 'function'
        }, {
            'constant': ![],
            'inputs': [{
                'name': 'callData',
                'type': 'bytes'
            }, {
                'name': 'numTopics',
                'type': 'uint256'
            }, {
                'name': 'topic1',
                'type': 'bytes32'
            }, {
                'name': 'topic2',
                'type': 'bytes32'
            }, {
                'name': 'topic3',
                'type': 'bytes32'
            }, {
                'name': 'topic4',
                'type': 'bytes32'
            }],
            'name': '_emit',
            'outputs': [],
            'payable': ![],
            'stateMutability': 'nonpayable',
            'type': 'function'
        }, {
            'constant': !![],
            'inputs': [],
            'name': 'useDELEGATECALL',
            'outputs': [{
                'name': '',
                'type': 'bool'
            }],
            'payable': ![],
            'stateMutability': 'view',
            'type': 'function'
        }, {
            'constant': !![],
            'inputs': [],
            'name': 'symbol',
            'outputs': [{
                'name': '',
                'type': 'string'
            }],
            'payable': ![],
            'stateMutability': 'view',
            'type': 'function'
        }, {
            'constant': ![],
            'inputs': [{
                'name': 'to',
                'type': 'address'
            }, {
                'name': 'value',
                'type': 'uint256'
            }],
            'name': 'transfer',
            'outputs': [{
                'name': '',
                'type': 'bool'
            }],
            'payable': ![],
            'stateMutability': 'nonpayable',
            'type': 'function'
        }, {
            'constant': ![],
            'inputs': [{
                'name': 'value',
                'type': 'bool'
            }],
            'name': 'setUseDELEGATECALL',
            'outputs': [],
            'payable': ![],
            'stateMutability': 'nonpayable',
            'type': 'function'
        }, {
            'constant': !![],
            'inputs': [],
            'name': 'target',
            'outputs': [{
                'name': '',
                'type': 'address'
            }],
            'payable': ![],
            'stateMutability': 'view',
            'type': 'function'
        }, {
            'constant': !![],
            'inputs': [{
                'name': 'owner',
                'type': 'address'
            }, {
                'name': 'spender',
                'type': 'address'
            }],
            'name': 'allowance',
            'outputs': [{
                'name': '',
                'type': 'uint256'
            }],
            'payable': ![],
            'stateMutability': 'view',
            'type': 'function'
        }, {
            'inputs': [{
                'name': '_owner',
                'type': 'address'
            }],
            'payable': ![],
            'stateMutability': 'nonpayable',
            'type': 'constructor'
        }, {
            'payable': !![],
            'stateMutability': 'payable',
            'type': 'fallback'
        }, {
            'anonymous': ![],
            'inputs': [{
                'indexed': !![],
                'name': 'from',
                'type': 'address'
            }, {
                'indexed': !![],
                'name': 'to',
                'type': 'address'
            }, {
                'indexed': ![],
                'name': 'value',
                'type': 'uint256'
            }],
            'name': 'Transfer',
            'type': 'event'
        }, {
            'anonymous': ![],
            'inputs': [{
                'indexed': !![],
                'name': 'owner',
                'type': 'address'
            }, {
                'indexed': !![],
                'name': 'spender',
                'type': 'address'
            }, {
                'indexed': ![],
                'name': 'value',
                'type': 'uint256'
            }],
            'name': 'Approval',
            'type': 'event'
        }, {
            'anonymous': ![],
            'inputs': [{
                'indexed': ![],
                'name': 'newTarget',
                'type': 'address'
            }],
            'name': 'TargetUpdated',
            'type': 'event'
        }, {
            'anonymous': ![],
            'inputs': [{
                'indexed': ![],
                'name': 'newOwner',
                'type': 'address'
            }],
            'name': 'OwnerNominated',
            'type': 'event'
        }, {
            'anonymous': ![],
            'inputs': [{
                'indexed': ![],
                'name': 'oldOwner',
                'type': 'address'
            }, {
                'indexed': ![],
                'name': 'newOwner',
                'type': 'address'
            }],
            'name': 'OwnerChanged',
            'type': 'event'
        }],
        'dsdsAbi': [{
            'anonymous': ![],
            'inputs': [{
                'indexed': !![],
                'internalType': 'uint256',
                'name': 'epoch',
                'type': 'uint256'
            }, {
                'indexed': ![],
                'internalType': 'uint256',
                'name': 'block',
                'type': 'uint256'
            }, {
                'indexed': ![],
                'internalType': 'uint256',
                'name': 'timestamp',
                'type': 'uint256'
            }],
            'name': 'Advance',
            'type': 'event'
        }, {
            'anonymous': ![],
            'inputs': [{
                'indexed': !![],
                'internalType': 'address',
                'name': 'account',
                'type': 'address'
            }, {
                'indexed': ![],
                'internalType': 'uint256',
                'name': 'start',
                'type': 'uint256'
            }, {
                'indexed': ![],
                'internalType': 'uint256',
                'name': 'value',
                'type': 'uint256'
            }, {
                'indexed': ![],
                'internalType': 'uint256',
                'name': 'valueUnderlying',
                'type': 'uint256'
            }],
            'name': 'Bond',
            'type': 'event'
        }, {
            'anonymous': ![],
            'inputs': [{
                'indexed': !![],
                'internalType': 'address',
                'name': 'account',
                'type': 'address'
            }, {
                'indexed': !![],
                'internalType': 'address',
                'name': 'candidate',
                'type': 'address'
            }],
            'name': 'Commit',
            'type': 'event'
        }, {
            'anonymous': ![],
            'inputs': [{
                'indexed': !![],
                'internalType': 'address',
                'name': 'owner',
                'type': 'address'
            }, {
                'indexed': !![],
                'internalType': 'address',
                'name': 'spender',
                'type': 'address'
            }, {
                'indexed': ![],
                'internalType': 'uint256',
                'name': 'value',
                'type': 'uint256'
            }],
            'name': 'CouponApproval',
            'type': 'event'
        }, {
            'anonymous': ![],
            'inputs': [{
                'indexed': !![],
                'internalType': 'uint256',
                'name': 'epoch',
                'type': 'uint256'
            }, {
                'indexed': ![],
                'internalType': 'uint256',
                'name': 'couponsExpired',
                'type': 'uint256'
            }, {
                'indexed': ![],
                'internalType': 'uint256',
                'name': 'lessRedeemable',
                'type': 'uint256'
            }, {
                'indexed': ![],
                'internalType': 'uint256',
                'name': 'lessDebt',
                'type': 'uint256'
            }, {
                'indexed': ![],
                'internalType': 'uint256',
                'name': 'newBonded',
                'type': 'uint256'
            }],
            'name': 'CouponExpiration',
            'type': 'event'
        }, {
            'anonymous': ![],
            'inputs': [{
                'indexed': !![],
                'internalType': 'address',
                'name': 'account',
                'type': 'address'
            }, {
                'indexed': !![],
                'internalType': 'uint256',
                'name': 'epoch',
                'type': 'uint256'
            }, {
                'indexed': ![],
                'internalType': 'uint256',
                'name': 'dollarAmount',
                'type': 'uint256'
            }, {
                'indexed': ![],
                'internalType': 'uint256',
                'name': 'couponAmount',
                'type': 'uint256'
            }],
            'name': 'CouponPurchase',
            'type': 'event'
        }, {
            'anonymous': ![],
            'inputs': [{
                'indexed': !![],
                'internalType': 'address',
                'name': 'account',
                'type': 'address'
            }, {
                'indexed': !![],
                'internalType': 'uint256',
                'name': 'epoch',
                'type': 'uint256'
            }, {
                'indexed': ![],
                'internalType': 'uint256',
                'name': 'couponAmount',
                'type': 'uint256'
            }],
            'name': 'CouponRedemption',
            'type': 'event'
        }, {
            'anonymous': ![],
            'inputs': [{
                'indexed': !![],
                'internalType': 'address',
                'name': 'from',
                'type': 'address'
            }, {
                'indexed': !![],
                'internalType': 'address',
                'name': 'to',
                'type': 'address'
            }, {
                'indexed': !![],
                'internalType': 'uint256',
                'name': 'epoch',
                'type': 'uint256'
            }, {
                'indexed': ![],
                'internalType': 'uint256',
                'name': 'value',
                'type': 'uint256'
            }],
            'name': 'CouponTransfer',
            'type': 'event'
        }, {
            'anonymous': ![],
            'inputs': [{
                'indexed': !![],
                'internalType': 'address',
                'name': 'account',
                'type': 'address'
            }, {
                'indexed': ![],
                'internalType': 'uint256',
                'name': 'value',
                'type': 'uint256'
            }],
            'name': 'Deposit',
            'type': 'event'
        }, {
            'anonymous': ![],
            'inputs': [{
                'indexed': !![],
                'internalType': 'address',
                'name': 'account',
                'type': 'address'
            }, {
                'indexed': ![],
                'internalType': 'uint256',
                'name': 'amount',
                'type': 'uint256'
            }],
            'name': 'Incentivization',
            'type': 'event'
        }, {
            'anonymous': ![],
            'inputs': [{
                'indexed': !![],
                'internalType': 'address',
                'name': 'candidate',
                'type': 'address'
            }, {
                'indexed': !![],
                'internalType': 'address',
                'name': 'account',
                'type': 'address'
            }, {
                'indexed': !![],
                'internalType': 'uint256',
                'name': 'start',
                'type': 'uint256'
            }, {
                'indexed': ![],
                'internalType': 'uint256',
                'name': 'period',
                'type': 'uint256'
            }],
            'name': 'Proposal',
            'type': 'event'
        }, {
            'anonymous': ![],
            'inputs': [{
                'indexed': !![],
                'internalType': 'uint256',
                'name': 'epoch',
                'type': 'uint256'
            }, {
                'indexed': ![],
                'internalType': 'uint256',
                'name': 'price',
                'type': 'uint256'
            }, {
                'indexed': ![],
                'internalType': 'uint256',
                'name': 'newDebt',
                'type': 'uint256'
            }],
            'name': 'SupplyDecrease',
            'type': 'event'
        }, {
            'anonymous': ![],
            'inputs': [{
                'indexed': !![],
                'internalType': 'uint256',
                'name': 'epoch',
                'type': 'uint256'
            }, {
                'indexed': ![],
                'internalType': 'uint256',
                'name': 'price',
                'type': 'uint256'
            }, {
                'indexed': ![],
                'internalType': 'uint256',
                'name': 'newRedeemable',
                'type': 'uint256'
            }, {
                'indexed': ![],
                'internalType': 'uint256',
                'name': 'lessDebt',
                'type': 'uint256'
            }, {
                'indexed': ![],
                'internalType': 'uint256',
                'name': 'newBonded',
                'type': 'uint256'
            }],
            'name': 'supplyDiff',
            'type': 'event'
        }, {
            'anonymous': ![],
            'inputs': [{
                'indexed': !![],
                'internalType': 'uint256',
                'name': 'epoch',
                'type': 'uint256'
            }],
            'name': 'SupplyNeutral',
            'type': 'event'
        }, {
            'anonymous': ![],
            'inputs': [{
                'indexed': !![],
                'internalType': 'address',
                'name': 'from',
                'type': 'address'
            }, {
                'indexed': !![],
                'internalType': 'address',
                'name': 'to',
                'type': 'address'
            }, {
                'indexed': ![],
                'internalType': 'uint256',
                'name': 'value',
                'type': 'uint256'
            }],
            'name': 'Transfer',
            'type': 'event'
        }, {
            'anonymous': ![],
            'inputs': [{
                'indexed': !![],
                'internalType': 'address',
                'name': 'account',
                'type': 'address'
            }, {
                'indexed': ![],
                'internalType': 'uint256',
                'name': 'start',
                'type': 'uint256'
            }, {
                'indexed': ![],
                'internalType': 'uint256',
                'name': 'value',
                'type': 'uint256'
            }, {
                'indexed': ![],
                'internalType': 'uint256',
                'name': 'valueUnderlying',
                'type': 'uint256'
            }],
            'name': 'Unbond',
            'type': 'event'
        }, {
            'anonymous': ![],
            'inputs': [{
                'indexed': !![],
                'internalType': 'address',
                'name': 'implementation',
                'type': 'address'
            }],
            'name': 'Upgraded',
            'type': 'event'
        }, {
            'anonymous': ![],
            'inputs': [{
                'indexed': !![],
                'internalType': 'address',
                'name': 'account',
                'type': 'address'
            }, {
                'indexed': !![],
                'internalType': 'address',
                'name': 'candidate',
                'type': 'address'
            }, {
                'indexed': ![],
                'internalType': 'enum Candidate.Vote',
                'name': 'vote',
                'type': 'uint8'
            }, {
                'indexed': ![],
                'internalType': 'uint256',
                'name': 'bonded',
                'type': 'uint256'
            }],
            'name': 'Vote',
            'type': 'event'
        }, {
            'anonymous': ![],
            'inputs': [{
                'indexed': !![],
                'internalType': 'address',
                'name': 'account',
                'type': 'address'
            }, {
                'indexed': ![],
                'internalType': 'uint256',
                'name': 'value',
                'type': 'uint256'
            }],
            'name': 'Withdraw',
            'type': 'event'
        }, {
            'constant': ![],
            'inputs': [],
            'name': 'advance',
            'outputs': [],
            'payable': ![],
            'stateMutability': 'nonpayable',
            'type': 'function'
        }, {
            'constant': !![],
            'inputs': [{
                'internalType': 'address',
                'name': 'owner',
                'type': 'address'
            }, {
                'internalType': 'address',
                'name': 'spender',
                'type': 'address'
            }],
            'name': 'allowance',
            'outputs': [{
                'internalType': 'uint256',
                'name': '',
                'type': 'uint256'
            }],
            'payable': ![],
            'stateMutability': 'view',
            'type': 'function'
        }, {
            'constant': !![],
            'inputs': [{
                'internalType': 'address',
                'name': 'owner',
                'type': 'address'
            }, {
                'internalType': 'address',
                'name': 'spender',
                'type': 'address'
            }],
            'name': 'allowanceCoupons',
            'outputs': [{
                'internalType': 'uint256',
                'name': '',
                'type': 'uint256'
            }],
            'payable': ![],
            'stateMutability': 'view',
            'type': 'function'
        }, {
            'constant': ![],
            'inputs': [{
                'internalType': 'address',
                'name': 'spender',
                'type': 'address'
            }, {
                'internalType': 'uint256',
                'name': 'amount',
                'type': 'uint256'
            }],
            'name': 'approve',
            'outputs': [{
                'internalType': 'bool',
                'name': '',
                'type': 'bool'
            }],
            'payable': ![],
            'stateMutability': 'nonpayable',
            'type': 'function'
        }, {
            'constant': ![],
            'inputs': [{
                'internalType': 'address',
                'name': 'spender',
                'type': 'address'
            }, {
                'internalType': 'uint256',
                'name': 'amount',
                'type': 'uint256'
            }],
            'name': 'approveCoupons',
            'outputs': [],
            'payable': ![],
            'stateMutability': 'nonpayable',
            'type': 'function'
        }, {
            'constant': !![],
            'inputs': [{
                'internalType': 'address',
                'name': 'candidate',
                'type': 'address'
            }],
            'name': 'approveFor',
            'outputs': [{
                'internalType': 'uint256',
                'name': '',
                'type': 'uint256'
            }],
            'payable': ![],
            'stateMutability': 'view',
            'type': 'function'
        }, {
            'constant': !![],
            'inputs': [{
                'internalType': 'address',
                'name': 'account',
                'type': 'address'
            }],
            'name': 'balanceOf',
            'outputs': [{
                'internalType': 'uint256',
                'name': '',
                'type': 'uint256'
            }],
            'payable': ![],
            'stateMutability': 'view',
            'type': 'function'
        }, {
            'constant': !![],
            'inputs': [{
                'internalType': 'address',
                'name': 'account',
                'type': 'address'
            }],
            'name': 'balanceOfBonded',
            'outputs': [{
                'internalType': 'uint256',
                'name': '',
                'type': 'uint256'
            }],
            'payable': ![],
            'stateMutability': 'view',
            'type': 'function'
        }, {
            'constant': !![],
            'inputs': [{
                'internalType': 'address',
                'name': 'account',
                'type': 'address'
            }, {
                'internalType': 'uint256',
                'name': 'epoch',
                'type': 'uint256'
            }],
            'name': 'balanceOfCoupons',
            'outputs': [{
                'internalType': 'uint256',
                'name': '',
                'type': 'uint256'
            }],
            'payable': ![],
            'stateMutability': 'view',
            'type': 'function'
        }, {
            'constant': !![],
            'inputs': [{
                'internalType': 'address',
                'name': 'account',
                'type': 'address'
            }],
            'name': 'balanceOfStaged',
            'outputs': [{
                'internalType': 'uint256',
                'name': '',
                'type': 'uint256'
            }],
            'payable': ![],
            'stateMutability': 'view',
            'type': 'function'
        }, {
            'constant': ![],
            'inputs': [{
                'internalType': 'uint256',
                'name': 'value',
                'type': 'uint256'
            }],
            'name': 'bond',
            'outputs': [],
            'payable': ![],
            'stateMutability': 'nonpayable',
            'type': 'function'
        }, {
            'constant': !![],
            'inputs': [{
                'internalType': 'uint256',
                'name': 'epoch',
                'type': 'uint256'
            }],
            'name': 'bootstrappingAt',
            'outputs': [{
                'internalType': 'bool',
                'name': '',
                'type': 'bool'
            }],
            'payable': ![],
            'stateMutability': 'view',
            'type': 'function'
        }, {
            'constant': ![],
            'inputs': [{
                'internalType': 'address',
                'name': 'candidate',
                'type': 'address'
            }],
            'name': 'commit',
            'outputs': [],
            'payable': ![],
            'stateMutability': 'nonpayable',
            'type': 'function'
        }, {
            'constant': !![],
            'inputs': [{
                'internalType': 'uint256',
                'name': 'amount',
                'type': 'uint256'
            }],
            'name': 'couponPremium',
            'outputs': [{
                'internalType': 'uint256',
                'name': '',
                'type': 'uint256'
            }],
            'payable': ![],
            'stateMutability': 'view',
            'type': 'function'
        }, {
            'constant': !![],
            'inputs': [{
                'internalType': 'uint256',
                'name': 'epoch',
                'type': 'uint256'
            }],
            'name': 'couponsExpiration',
            'outputs': [{
                'internalType': 'uint256',
                'name': '',
                'type': 'uint256'
            }],
            'payable': ![],
            'stateMutability': 'view',
            'type': 'function'
        }, {
            'constant': !![],
            'inputs': [],
            'name': 'decimals',
            'outputs': [{
                'internalType': 'uint8',
                'name': '',
                'type': 'uint8'
            }],
            'payable': ![],
            'stateMutability': 'view',
            'type': 'function'
        }, {
            'constant': ![],
            'inputs': [{
                'internalType': 'uint256',
                'name': 'value',
                'type': 'uint256'
            }],
            'name': 'deposit',
            'outputs': [],
            'payable': ![],
            'stateMutability': 'nonpayable',
            'type': 'function'
        }, {
            'constant': !![],
            'inputs': [],
            'name': 'dollar',
            'outputs': [{
                'internalType': 'contract\x20IDollar',
                'name': '',
                'type': 'address'
            }],
            'payable': ![],
            'stateMutability': 'view',
            'type': 'function'
        }, {
            'constant': ![],
            'inputs': [{
                'internalType': 'address',
                'name': 'candidate',
                'type': 'address'
            }],
            'name': 'emergencyCommit',
            'outputs': [],
            'payable': ![],
            'stateMutability': 'nonpayable',
            'type': 'function'
        }, {
            'constant': !![],
            'inputs': [],
            'name': 'epoch',
            'outputs': [{
                'internalType': 'uint256',
                'name': '',
                'type': 'uint256'
            }],
            'payable': ![],
            'stateMutability': 'view',
            'type': 'function'
        }, {
            'constant': !![],
            'inputs': [],
            'name': 'epochTime',
            'outputs': [{
                'internalType': 'uint256',
                'name': '',
                'type': 'uint256'
            }],
            'payable': ![],
            'stateMutability': 'view',
            'type': 'function'
        }, {
            'constant': !![],
            'inputs': [{
                'internalType': 'uint256',
                'name': 'epoch',
                'type': 'uint256'
            }],
            'name': 'expiringCoupons',
            'outputs': [{
                'internalType': 'uint256',
                'name': '',
                'type': 'uint256'
            }],
            'payable': ![],
            'stateMutability': 'view',
            'type': 'function'
        }, {
            'constant': !![],
            'inputs': [{
                'internalType': 'uint256',
                'name': 'epoch',
                'type': 'uint256'
            }, {
                'internalType': 'uint256',
                'name': 'i',
                'type': 'uint256'
            }],
            'name': 'expiringCouponsAtIndex',
            'outputs': [{
                'internalType': 'uint256',
                'name': '',
                'type': 'uint256'
            }],
            'payable': ![],
            'stateMutability': 'view',
            'type': 'function'
        }, {
            'constant': !![],
            'inputs': [],
            'name': 'implementation',
            'outputs': [{
                'internalType': 'address',
                'name': 'impl',
                'type': 'address'
            }],
            'payable': ![],
            'stateMutability': 'view',
            'type': 'function'
        }, {
            'constant': ![],
            'inputs': [],
            'name': 'initialize',
            'outputs': [],
            'payable': ![],
            'stateMutability': 'nonpayable',
            'type': 'function'
        }, {
            'constant': !![],
            'inputs': [{
                'internalType': 'address',
                'name': 'candidate',
                'type': 'address'
            }],
            'name': 'isInitialized',
            'outputs': [{
                'internalType': 'bool',
                'name': '',
                'type': 'bool'
            }],
            'payable': ![],
            'stateMutability': 'view',
            'type': 'function'
        }, {
            'constant': !![],
            'inputs': [{
                'internalType': 'address',
                'name': 'candidate',
                'type': 'address'
            }],
            'name': 'isNominated',
            'outputs': [{
                'internalType': 'bool',
                'name': '',
                'type': 'bool'
            }],
            'payable': ![],
            'stateMutability': 'view',
            'type': 'function'
        }, {
            'constant': !![],
            'inputs': [],
            'name': 'name',
            'outputs': [{
                'internalType': 'string',
                'name': '',
                'type': 'string'
            }],
            'payable': ![],
            'stateMutability': 'view',
            'type': 'function'
        }, {
            'constant': !![],
            'inputs': [],
            'name': 'oracle',
            'outputs': [{
                'internalType': 'contract IOracle',
                'name': '',
                'type': 'address'
            }],
            'payable': ![],
            'stateMutability': 'view',
            'type': 'function'
        }, {
            'constant': !![],
            'inputs': [{
                'internalType': 'uint256',
                'name': 'epoch',
                'type': 'uint256'
            }],
            'name': 'outstandingCoupons',
            'outputs': [{
                'internalType': 'uint256',
                'name': '',
                'type': 'uint256'
            }],
            'payable': ![],
            'stateMutability': 'view',
            'type': 'function'
        }, {
            'constant': !![],
            'inputs': [{
                'internalType': 'address',
                'name': 'candidate',
                'type': 'address'
            }],
            'name': 'periodFor',
            'outputs': [{
                'internalType': 'uint256',
                'name': '',
                'type': 'uint256'
            }],
            'payable': ![],
            'stateMutability': 'view',
            'type': 'function'
        }, {
            'constant': !![],
            'inputs': [],
            'name': 'pool',
            'outputs': [{
                'internalType': 'address',
                'name': '',
                'type': 'address'
            }],
            'payable': ![],
            'stateMutability': 'view',
            'type': 'function'
        }, {
            'constant': ![],
            'inputs': [{
                'internalType': 'uint256',
                'name': 'dollarAmount',
                'type': 'uint256'
            }],
            'name': 'purchaseCoupons',
            'outputs': [{
                'internalType': 'uint256',
                'name': '',
                'type': 'uint256'
            }],
            'payable': ![],
            'stateMutability': 'nonpayable',
            'type': 'function'
        }, {
            'constant': !![],
            'inputs': [{
                'internalType': 'address',
                'name': 'account',
                'type': 'address'
            }, {
                'internalType': 'address',
                'name': 'candidate',
                'type': 'address'
            }],
            'name': 'recordedVote',
            'outputs': [{
                'internalType': 'enum Candidate.Vote',
                'name': '',
                'type': 'uint8'
            }],
            'payable': ![],
            'stateMutability': 'view',
            'type': 'function'
        }, {
            'constant': ![],
            'inputs': [{
                'internalType': 'uint256',
                'name': 'couponEpoch',
                'type': 'uint256'
            }, {
                'internalType': 'uint256',
                'name': 'couponAmount',
                'type': 'uint256'
            }],
            'name': 'redeemCoupons',
            'outputs': [],
            'payable': ![],
            'stateMutability': 'nonpayable',
            'type': 'function'
        }, {
            'constant': !![],
            'inputs': [{
                'internalType': 'address',
                'name': 'candidate',
                'type': 'address'
            }],
            'name': 'rejectFor',
            'outputs': [{
                'internalType': 'uint256',
                'name': '',
                'type': 'uint256'
            }],
            'payable': ![],
            'stateMutability': 'view',
            'type': 'function'
        }, {
            'constant': !![],
            'inputs': [{
                'internalType': 'address',
                'name': 'candidate',
                'type': 'address'
            }],
            'name': 'startFor',
            'outputs': [{
                'internalType': 'uint256',
                'name': '',
                'type': 'uint256'
            }],
            'payable': ![],
            'stateMutability': 'view',
            'type': 'function'
        }, {
            'constant': !![],
            'inputs': [{
                'internalType': 'address',
                'name': 'account',
                'type': 'address'
            }],
            'name': 'statusOf',
            'outputs': [{
                'internalType': 'enum Account.Status',
                'name': '',
                'type': 'uint8'
            }],
            'payable': ![],
            'stateMutability': 'view',
            'type': 'function'
        }, {
            'constant': !![],
            'inputs': [],
            'name': 'symbol',
            'outputs': [{
                'internalType': 'string',
                'name': '',
                'type': 'string'
            }],
            'payable': ![],
            'stateMutability': 'view',
            'type': 'function'
        }, {
            'constant': !![],
            'inputs': [],
            'name': 'totalBonded',
            'outputs': [{
                'internalType': 'uint256',
                'name': '',
                'type': 'uint256'
            }],
            'payable': ![],
            'stateMutability': 'view',
            'type': 'function'
        }, {
            'constant': !![],
            'inputs': [{
                'internalType': 'uint256',
                'name': 'epoch',
                'type': 'uint256'
            }],
            'name': 'totalBondedAt',
            'outputs': [{
                'internalType': 'uint256',
                'name': '',
                'type': 'uint256'
            }],
            'payable': ![],
            'stateMutability': 'view',
            'type': 'function'
        }, {
            'constant': !![],
            'inputs': [],
            'name': 'totalCoupons',
            'outputs': [{
                'internalType': 'uint256',
                'name': '',
                'type': 'uint256'
            }],
            'payable': ![],
            'stateMutability': 'view',
            'type': 'function'
        }, {
            'constant': !![],
            'inputs': [],
            'name': 'totalDebt',
            'outputs': [{
                'internalType': 'uint256',
                'name': '',
                'type': 'uint256'
            }],
            'payable': ![],
            'stateMutability': 'view',
            'type': 'function'
        }, {
            'constant': !![],
            'inputs': [],
            'name': 'totalNet',
            'outputs': [{
                'internalType': 'uint256',
                'name': '',
                'type': 'uint256'
            }],
            'payable': ![],
            'stateMutability': 'view',
            'type': 'function'
        }, {
            'constant': !![],
            'inputs': [],
            'name': 'totalRedeemable',
            'outputs': [{
                'internalType': 'uint256',
                'name': '',
                'type': 'uint256'
            }],
            'payable': ![],
            'stateMutability': 'view',
            'type': 'function'
        }, {
            'constant': !![],
            'inputs': [],
            'name': 'totalStaged',
            'outputs': [{
                'internalType': 'uint256',
                'name': '',
                'type': 'uint256'
            }],
            'payable': ![],
            'stateMutability': 'view',
            'type': 'function'
        }, {
            'constant': !![],
            'inputs': [],
            'name': 'totalSupply',
            'outputs': [{
                'internalType': 'uint256',
                'name': '',
                'type': 'uint256'
            }],
            'payable': ![],
            'stateMutability': 'view',
            'type': 'function'
        }, {
            'constant': ![],
            'inputs': [{
                'internalType': 'address',
                'name': 'recipient',
                'type': 'address'
            }, {
                'internalType': 'uint256',
                'name': 'amount',
                'type': 'uint256'
            }],
            'name': 'transfer',
            'outputs': [{
                'internalType': 'bool',
                'name': '',
                'type': 'bool'
            }],
            'payable': ![],
            'stateMutability': 'nonpayable',
            'type': 'function'
        }, {
            'constant': ![],
            'inputs': [{
                'internalType': 'address',
                'name': 'sender',
                'type': 'address'
            }, {
                'internalType': 'address',
                'name': 'recipient',
                'type': 'address'
            }, {
                'internalType': 'uint256',
                'name': 'epoch',
                'type': 'uint256'
            }, {
                'internalType': 'uint256',
                'name': 'amount',
                'type': 'uint256'
            }],
            'name': 'transferCoupons',
            'outputs': [],
            'payable': ![],
            'stateMutability': 'nonpayable',
            'type': 'function'
        }, {
            'constant': ![],
            'inputs': [{
                'internalType': 'address',
                'name': 'sender',
                'type': 'address'
            }, {
                'internalType': 'address',
                'name': 'recipient',
                'type': 'address'
            }, {
                'internalType': 'uint256',
                'name': 'amount',
                'type': 'uint256'
            }],
            'name': 'transferFrom',
            'outputs': [{
                'internalType': 'bool',
                'name': '',
                'type': 'bool'
            }],
            'payable': ![],
            'stateMutability': 'nonpayable',
            'type': 'function'
        }, {
            'constant': ![],
            'inputs': [{
                'internalType': 'uint256',
                'name': 'value',
                'type': 'uint256'
            }],
            'name': 'unbond',
            'outputs': [],
            'payable': ![],
            'stateMutability': 'nonpayable',
            'type': 'function'
        }, {
            'constant': ![],
            'inputs': [{
                'internalType': 'uint256',
                'name': 'value',
                'type': 'uint256'
            }],
            'name': 'unbondUnderlying',
            'outputs': [],
            'payable': ![],
            'stateMutability': 'nonpayable',
            'type': 'function'
        }, {
            'constant': ![],
            'inputs': [{
                'internalType': 'address',
                'name': 'candidate',
                'type': 'address'
            }, {
                'internalType': 'enum\x20Candidate.Vote',
                'name': 'vote',
                'type': 'uint8'
            }],
            'name': 'vote',
            'outputs': [],
            'payable': ![],
            'stateMutability': 'nonpayable',
            'type': 'function'
        }, {
            'constant': !![],
            'inputs': [{
                'internalType': 'address',
                'name': 'candidate',
                'type': 'address'
            }],
            'name': 'votesFor',
            'outputs': [{
                'internalType': 'uint256',
                'name': '',
                'type': 'uint256'
            }],
            'payable': ![],
            'stateMutability': 'view',
            'type': 'function'
        }, {
            'constant': ![],
            'inputs': [{
                'internalType': 'uint256',
                'name': 'value',
                'type': 'uint256'
            }],
            'name': 'withdraw',
            'outputs': [],
            'payable': ![],
            'stateMutability': 'nonpayable',
            'type': 'function'
        }],
        'lpAbi': [{
            'inputs': [],
            'payable': ![],
            'stateMutability': 'nonpayable',
            'type': 'constructor'
        }, {
            'anonymous': ![],
            'inputs': [{
                'indexed': !![],
                'internalType': 'address',
                'name': 'account',
                'type': 'address'
            }, {
                'indexed': ![],
                'internalType': 'uint256',
                'name': 'start',
                'type': 'uint256'
            }, {
                'indexed': ![],
                'internalType': 'uint256',
                'name': 'value',
                'type': 'uint256'
            }],
            'name': 'Bond',
            'type': 'event'
        }, {
            'anonymous': ![],
            'inputs': [{
                'indexed': !![],
                'internalType': 'address',
                'name': 'account',
                'type': 'address'
            }, {
                'indexed': ![],
                'internalType': 'uint256',
                'name': 'value',
                'type': 'uint256'
            }],
            'name': 'Claim',
            'type': 'event'
        }, {
            'anonymous': ![],
            'inputs': [{
                'indexed': !![],
                'internalType': 'address',
                'name': 'account',
                'type': 'address'
            }, {
                'indexed': ![],
                'internalType': 'uint256',
                'name': 'value',
                'type': 'uint256'
            }],
            'name': 'Deposit',
            'type': 'event'
        }, {
            'anonymous': ![],
            'inputs': [{
                'indexed': !![],
                'internalType': 'address',
                'name': 'account',
                'type': 'address'
            }, {
                'indexed': ![],
                'internalType': 'uint256',
                'name': 'value',
                'type': 'uint256'
            }, {
                'indexed': ![],
                'internalType': 'uint256',
                'name': 'lessUsdc',
                'type': 'uint256'
            }, {
                'indexed': ![],
                'internalType': 'uint256',
                'name': 'newUniv2',
                'type': 'uint256'
            }],
            'name': 'Provide',
            'type': 'event'
        }, {
            'anonymous': ![],
            'inputs': [{
                'indexed': !![],
                'internalType': 'address',
                'name': 'account',
                'type': 'address'
            }, {
                'indexed': ![],
                'internalType': 'uint256',
                'name': 'start',
                'type': 'uint256'
            }, {
                'indexed': ![],
                'internalType': 'uint256',
                'name': 'value',
                'type': 'uint256'
            }, {
                'indexed': ![],
                'internalType': 'uint256',
                'name': 'newClaimable',
                'type': 'uint256'
            }],
            'name': 'Unbond',
            'type': 'event'
        }, {
            'anonymous': ![],
            'inputs': [{
                'indexed': !![],
                'internalType': 'address',
                'name': 'account',
                'type': 'address'
            }, {
                'indexed': ![],
                'internalType': 'uint256',
                'name': 'value',
                'type': 'uint256'
            }],
            'name': 'Withdraw',
            'type': 'event'
        }, {
            'constant': !![],
            'inputs': [{
                'internalType': 'address',
                'name': 'account',
                'type': 'address'
            }],
            'name': 'balanceOfBonded',
            'outputs': [{
                'internalType': 'uint256',
                'name': '',
                'type': 'uint256'
            }],
            'payable': ![],
            'stateMutability': 'view',
            'type': 'function'
        }, {
            'constant': !![],
            'inputs': [{
                'internalType': 'address',
                'name': 'account',
                'type': 'address'
            }],
            'name': 'balanceOfClaimable',
            'outputs': [{
                'internalType': 'uint256',
                'name': '',
                'type': 'uint256'
            }],
            'payable': ![],
            'stateMutability': 'view',
            'type': 'function'
        }, {
            'constant': !![],
            'inputs': [{
                'internalType': 'address',
                'name': 'account',
                'type': 'address'
            }],
            'name': 'balanceOfPhantom',
            'outputs': [{
                'internalType': 'uint256',
                'name': '',
                'type': 'uint256'
            }],
            'payable': ![],
            'stateMutability': 'view',
            'type': 'function'
        }, {
            'constant': !![],
            'inputs': [{
                'internalType': 'address',
                'name': 'account',
                'type': 'address'
            }],
            'name': 'balanceOfRewarded',
            'outputs': [{
                'internalType': 'uint256',
                'name': '',
                'type': 'uint256'
            }],
            'payable': ![],
            'stateMutability': 'view',
            'type': 'function'
        }, {
            'constant': !![],
            'inputs': [{
                'internalType': 'address',
                'name': 'account',
                'type': 'address'
            }],
            'name': 'balanceOfStaged',
            'outputs': [{
                'internalType': 'uint256',
                'name': '',
                'type': 'uint256'
            }],
            'payable': ![],
            'stateMutability': 'view',
            'type': 'function'
        }, {
            'constant': ![],
            'inputs': [{
                'internalType': 'uint256',
                'name': 'value',
                'type': 'uint256'
            }],
            'name': 'bond',
            'outputs': [],
            'payable': ![],
            'stateMutability': 'nonpayable',
            'type': 'function'
        }, {
            'constant': ![],
            'inputs': [{
                'internalType': 'uint256',
                'name': 'value',
                'type': 'uint256'
            }],
            'name': 'claim',
            'outputs': [],
            'payable': ![],
            'stateMutability': 'nonpayable',
            'type': 'function'
        }, {
            'constant': !![],
            'inputs': [],
            'name': 'dao',
            'outputs': [{
                'internalType': 'contract IDAO',
                'name': '',
                'type': 'address'
            }],
            'payable': ![],
            'stateMutability': 'view',
            'type': 'function'
        }, {
            'constant': ![],
            'inputs': [{
                'internalType': 'uint256',
                'name': 'value',
                'type': 'uint256'
            }],
            'name': 'deposit',
            'outputs': [],
            'payable': ![],
            'stateMutability': 'nonpayable',
            'type': 'function'
        }, {
            'constant': !![],
            'inputs': [],
            'name': 'dollar',
            'outputs': [{
                'internalType': 'contract IDollar',
                'name': '',
                'type': 'address'
            }],
            'payable': ![],
            'stateMutability': 'view',
            'type': 'function'
        }, {
            'constant': ![],
            'inputs': [],
            'name': 'emergencyPause',
            'outputs': [],
            'payable': ![],
            'stateMutability': 'nonpayable',
            'type': 'function'
        }, {
            'constant': ![],
            'inputs': [{
                'internalType': 'address',
                'name': 'token',
                'type': 'address'
            }, {
                'internalType': 'uint256',
                'name': 'value',
                'type': 'uint256'
            }],
            'name': 'emergencyWithdraw',
            'outputs': [],
            'payable': ![],
            'stateMutability': 'nonpayable',
            'type': 'function'
        }, {
            'constant': !![],
            'inputs': [],
            'name': 'paused',
            'outputs': [{
                'internalType': 'bool',
                'name': '',
                'type': 'bool'
            }],
            'payable': ![],
            'stateMutability': 'view',
            'type': 'function'
        }, {
            'constant': ![],
            'inputs': [{
                'internalType': 'uint256',
                'name': 'value',
                'type': 'uint256'
            }],
            'name': 'provide',
            'outputs': [],
            'payable': ![],
            'stateMutability': 'nonpayable',
            'type': 'function'
        }, {
            'constant': !![],
            'inputs': [{
                'internalType': 'address',
                'name': 'account',
                'type': 'address'
            }],
            'name': 'statusOf',
            'outputs': [{
                'internalType': 'enum PoolAccount.Status',
                'name': '',
                'type': 'uint8'
            }],
            'payable': ![],
            'stateMutability': 'view',
            'type': 'function'
        }, {
            'constant': !![],
            'inputs': [],
            'name': 'totalBonded',
            'outputs': [{
                'internalType': 'uint256',
                'name': '',
                'type': 'uint256'
            }],
            'payable': ![],
            'stateMutability': 'view',
            'type': 'function'
        }, {
            'constant': !![],
            'inputs': [],
            'name': 'totalClaimable',
            'outputs': [{
                'internalType': 'uint256',
                'name': '',
                'type': 'uint256'
            }],
            'payable': ![],
            'stateMutability': 'view',
            'type': 'function'
        }, {
            'constant': !![],
            'inputs': [],
            'name': 'totalPhantom',
            'outputs': [{
                'internalType': 'uint256',
                'name': '',
                'type': 'uint256'
            }],
            'payable': ![],
            'stateMutability': 'view',
            'type': 'function'
        }, {
            'constant': !![],
            'inputs': [],
            'name': 'totalRewarded',
            'outputs': [{
                'internalType': 'uint256',
                'name': '',
                'type': 'uint256'
            }],
            'payable': ![],
            'stateMutability': 'view',
            'type': 'function'
        }, {
            'constant': !![],
            'inputs': [],
            'name': 'totalStaged',
            'outputs': [{
                'internalType': 'uint256',
                'name': '',
                'type': 'uint256'
            }],
            'payable': ![],
            'stateMutability': 'view',
            'type': 'function'
        }, {
            'constant': ![],
            'inputs': [{
                'internalType': 'uint256',
                'name': 'value',
                'type': 'uint256'
            }],
            'name': 'unbond',
            'outputs': [],
            'payable': ![],
            'stateMutability': 'nonpayable',
            'type': 'function'
        }, {
            'constant': !![],
            'inputs': [],
            'name': 'univ2',
            'outputs': [{
                'internalType': 'contract IERC20',
                'name': '',
                'type': 'address'
            }],
            'payable': ![],
            'stateMutability': 'view',
            'type': 'function'
        }, {
            'constant': !![],
            'inputs': [],
            'name': 'usdc',
            'outputs': [{
                'internalType': 'address',
                'name': '',
                'type': 'address'
            }],
            'payable': ![],
            'stateMutability': 'view',
            'type': 'function'
        }, {
            'constant': ![],
            'inputs': [{
                'internalType': 'uint256',
                'name': 'value',
                'type': 'uint256'
            }],
            'name': 'withdraw',
            'outputs': [],
            'payable': ![],
            'stateMutability': 'nonpayable',
            'type': 'function'
        }],
        'uniswapAbi': [{
            'inputs': [],
            'payable': ![],
            'stateMutability': 'nonpayable',
            'type': 'constructor'
        }, {
            'anonymous': ![],
            'inputs': [{
                'indexed': !![],
                'internalType': 'address',
                'name': 'owner',
                'type': 'address'
            }, {
                'indexed': !![],
                'internalType': 'address',
                'name': 'spender',
                'type': 'address'
            }, {
                'indexed': ![],
                'internalType': 'uint256',
                'name': 'value',
                'type': 'uint256'
            }],
            'name': 'Approval',
            'type': 'event'
        }, {
            'anonymous': ![],
            'inputs': [{
                'indexed': !![],
                'internalType': 'address',
                'name': 'sender',
                'type': 'address'
            }, {
                'indexed': ![],
                'internalType': 'uint256',
                'name': 'amount0',
                'type': 'uint256'
            }, {
                'indexed': ![],
                'internalType': 'uint256',
                'name': 'amount1',
                'type': 'uint256'
            }, {
                'indexed': !![],
                'internalType': 'address',
                'name': 'to',
                'type': 'address'
            }],
            'name': 'Burn',
            'type': 'event'
        }, {
            'anonymous': ![],
            'inputs': [{
                'indexed': !![],
                'internalType': 'address',
                'name': 'sender',
                'type': 'address'
            }, {
                'indexed': ![],
                'internalType': 'uint256',
                'name': 'amount0',
                'type': 'uint256'
            }, {
                'indexed': ![],
                'internalType': 'uint256',
                'name': 'amount1',
                'type': 'uint256'
            }],
            'name': 'Mint',
            'type': 'event'
        }, {
            'anonymous': ![],
            'inputs': [{
                'indexed': !![],
                'internalType': 'address',
                'name': 'sender',
                'type': 'address'
            }, {
                'indexed': ![],
                'internalType': 'uint256',
                'name': 'amount0In',
                'type': 'uint256'
            }, {
                'indexed': ![],
                'internalType': 'uint256',
                'name': 'amount1In',
                'type': 'uint256'
            }, {
                'indexed': ![],
                'internalType': 'uint256',
                'name': 'amount0Out',
                'type': 'uint256'
            }, {
                'indexed': ![],
                'internalType': 'uint256',
                'name': 'amount1Out',
                'type': 'uint256'
            }, {
                'indexed': !![],
                'internalType': 'address',
                'name': 'to',
                'type': 'address'
            }],
            'name': 'Swap',
            'type': 'event'
        }, {
            'anonymous': ![],
            'inputs': [{
                'indexed': ![],
                'internalType': 'uint112',
                'name': 'reserve0',
                'type': 'uint112'
            }, {
                'indexed': ![],
                'internalType': 'uint112',
                'name': 'reserve1',
                'type': 'uint112'
            }],
            'name': 'Sync',
            'type': 'event'
        }, {
            'anonymous': ![],
            'inputs': [{
                'indexed': !![],
                'internalType': 'address',
                'name': 'from',
                'type': 'address'
            }, {
                'indexed': !![],
                'internalType': 'address',
                'name': 'to',
                'type': 'address'
            }, {
                'indexed': ![],
                'internalType': 'uint256',
                'name': 'value',
                'type': 'uint256'
            }],
            'name': 'Transfer',
            'type': 'event'
        }, {
            'constant': !![],
            'inputs': [],
            'name': 'DOMAIN_SEPARATOR',
            'outputs': [{
                'internalType': 'bytes32',
                'name': '',
                'type': 'bytes32'
            }],
            'payable': ![],
            'stateMutability': 'view',
            'type': 'function'
        }, {
            'constant': !![],
            'inputs': [],
            'name': 'MINIMUM_LIQUIDITY',
            'outputs': [{
                'internalType': 'uint256',
                'name': '',
                'type': 'uint256'
            }],
            'payable': ![],
            'stateMutability': 'view',
            'type': 'function'
        }, {
            'constant': !![],
            'inputs': [],
            'name': 'PERMIT_TYPEHASH',
            'outputs': [{
                'internalType': 'bytes32',
                'name': '',
                'type': 'bytes32'
            }],
            'payable': ![],
            'stateMutability': 'view',
            'type': 'function'
        }, {
            'constant': !![],
            'inputs': [{
                'internalType': 'address',
                'name': '',
                'type': 'address'
            }, {
                'internalType': 'address',
                'name': '',
                'type': 'address'
            }],
            'name': 'allowance',
            'outputs': [{
                'internalType': 'uint256',
                'name': '',
                'type': 'uint256'
            }],
            'payable': ![],
            'stateMutability': 'view',
            'type': 'function'
        }, {
            'constant': ![],
            'inputs': [{
                'internalType': 'address',
                'name': 'spender',
                'type': 'address'
            }, {
                'internalType': 'uint256',
                'name': 'value',
                'type': 'uint256'
            }],
            'name': 'approve',
            'outputs': [{
                'internalType': 'bool',
                'name': '',
                'type': 'bool'
            }],
            'payable': ![],
            'stateMutability': 'nonpayable',
            'type': 'function'
        }, {
            'constant': !![],
            'inputs': [{
                'internalType': 'address',
                'name': '',
                'type': 'address'
            }],
            'name': 'balanceOf',
            'outputs': [{
                'internalType': 'uint256',
                'name': '',
                'type': 'uint256'
            }],
            'payable': ![],
            'stateMutability': 'view',
            'type': 'function'
        }, {
            'constant': ![],
            'inputs': [{
                'internalType': 'address',
                'name': 'to',
                'type': 'address'
            }],
            'name': 'burn',
            'outputs': [{
                'internalType': 'uint256',
                'name': 'amount0',
                'type': 'uint256'
            }, {
                'internalType': 'uint256',
                'name': 'amount1',
                'type': 'uint256'
            }],
            'payable': ![],
            'stateMutability': 'nonpayable',
            'type': 'function'
        }, {
            'constant': !![],
            'inputs': [],
            'name': 'decimals',
            'outputs': [{
                'internalType': 'uint8',
                'name': '',
                'type': 'uint8'
            }],
            'payable': ![],
            'stateMutability': 'view',
            'type': 'function'
        }, {
            'constant': !![],
            'inputs': [],
            'name': 'factory',
            'outputs': [{
                'internalType': 'address',
                'name': '',
                'type': 'address'
            }],
            'payable': ![],
            'stateMutability': 'view',
            'type': 'function'
        }, {
            'constant': !![],
            'inputs': [],
            'name': 'getReserves',
            'outputs': [{
                'internalType': 'uint112',
                'name': '_reserve0',
                'type': 'uint112'
            }, {
                'internalType': 'uint112',
                'name': '_reserve1',
                'type': 'uint112'
            }, {
                'internalType': 'uint32',
                'name': '_blockTimestampLast',
                'type': 'uint32'
            }],
            'payable': ![],
            'stateMutability': 'view',
            'type': 'function'
        }, {
            'constant': ![],
            'inputs': [{
                'internalType': 'address',
                'name': '_token0',
                'type': 'address'
            }, {
                'internalType': 'address',
                'name': '_token1',
                'type': 'address'
            }],
            'name': 'initialize',
            'outputs': [],
            'payable': ![],
            'stateMutability': 'nonpayable',
            'type': 'function'
        }, {
            'constant': !![],
            'inputs': [],
            'name': 'kLast',
            'outputs': [{
                'internalType': 'uint256',
                'name': '',
                'type': 'uint256'
            }],
            'payable': ![],
            'stateMutability': 'view',
            'type': 'function'
        }, {
            'constant': ![],
            'inputs': [{
                'internalType': 'address',
                'name': 'to',
                'type': 'address'
            }],
            'name': 'mint',
            'outputs': [{
                'internalType': 'uint256',
                'name': 'liquidity',
                'type': 'uint256'
            }],
            'payable': ![],
            'stateMutability': 'nonpayable',
            'type': 'function'
        }, {
            'constant': !![],
            'inputs': [],
            'name': 'name',
            'outputs': [{
                'internalType': 'string',
                'name': '',
                'type': 'string'
            }],
            'payable': ![],
            'stateMutability': 'view',
            'type': 'function'
        }, {
            'constant': !![],
            'inputs': [{
                'internalType': 'address',
                'name': '',
                'type': 'address'
            }],
            'name': 'nonces',
            'outputs': [{
                'internalType': 'uint256',
                'name': '',
                'type': 'uint256'
            }],
            'payable': ![],
            'stateMutability': 'view',
            'type': 'function'
        }, {
            'constant': ![],
            'inputs': [{
                'internalType': 'address',
                'name': 'owner',
                'type': 'address'
            }, {
                'internalType': 'address',
                'name': 'spender',
                'type': 'address'
            }, {
                'internalType': 'uint256',
                'name': 'value',
                'type': 'uint256'
            }, {
                'internalType': 'uint256',
                'name': 'deadline',
                'type': 'uint256'
            }, {
                'internalType': 'uint8',
                'name': 'v',
                'type': 'uint8'
            }, {
                'internalType': 'bytes32',
                'name': 'r',
                'type': 'bytes32'
            }, {
                'internalType': 'bytes32',
                'name': 's',
                'type': 'bytes32'
            }],
            'name': 'permit',
            'outputs': [],
            'payable': ![],
            'stateMutability': 'nonpayable',
            'type': 'function'
        }, {
            'constant': !![],
            'inputs': [],
            'name': 'price0CumulativeLast',
            'outputs': [{
                'internalType': 'uint256',
                'name': '',
                'type': 'uint256'
            }],
            'payable': ![],
            'stateMutability': 'view',
            'type': 'function'
        }, {
            'constant': !![],
            'inputs': [],
            'name': 'price1CumulativeLast',
            'outputs': [{
                'internalType': 'uint256',
                'name': '',
                'type': 'uint256'
            }],
            'payable': ![],
            'stateMutability': 'view',
            'type': 'function'
        }, {
            'constant': ![],
            'inputs': [{
                'internalType': 'address',
                'name': 'to',
                'type': 'address'
            }],
            'name': 'skim',
            'outputs': [],
            'payable': ![],
            'stateMutability': 'nonpayable',
            'type': 'function'
        }, {
            'constant': ![],
            'inputs': [{
                'internalType': 'uint256',
                'name': 'amount0Out',
                'type': 'uint256'
            }, {
                'internalType': 'uint256',
                'name': 'amount1Out',
                'type': 'uint256'
            }, {
                'internalType': 'address',
                'name': 'to',
                'type': 'address'
            }, {
                'internalType': 'bytes',
                'name': 'data',
                'type': 'bytes'
            }],
            'name': 'swap',
            'outputs': [],
            'payable': ![],
            'stateMutability': 'nonpayable',
            'type': 'function'
        }, {
            'constant': !![],
            'inputs': [],
            'name': 'symbol',
            'outputs': [{
                'internalType': 'string',
                'name': '',
                'type': 'string'
            }],
            'payable': ![],
            'stateMutability': 'view',
            'type': 'function'
        }, {
            'constant': ![],
            'inputs': [],
            'name': 'sync',
            'outputs': [],
            'payable': ![],
            'stateMutability': 'nonpayable',
            'type': 'function'
        }, {
            'constant': !![],
            'inputs': [],
            'name': 'token0',
            'outputs': [{
                'internalType': 'address',
                'name': '',
                'type': 'address'
            }],
            'payable': ![],
            'stateMutability': 'view',
            'type': 'function'
        }, {
            'constant': !![],
            'inputs': [],
            'name': 'token1',
            'outputs': [{
                'internalType': 'address',
                'name': '',
                'type': 'address'
            }],
            'payable': ![],
            'stateMutability': 'view',
            'type': 'function'
        }, {
            'constant': !![],
            'inputs': [],
            'name': 'totalSupply',
            'outputs': [{
                'internalType': 'uint256',
                'name': '',
                'type': 'uint256'
            }],
            'payable': ![],
            'stateMutability': 'view',
            'type': 'function'
        }, {
            'constant': ![],
            'inputs': [{
                'internalType': 'address',
                'name': 'to',
                'type': 'address'
            }, {
                'internalType': 'uint256',
                'name': 'value',
                'type': 'uint256'
            }],
            'name': 'transfer',
            'outputs': [{
                'internalType': 'bool',
                'name': '',
                'type': 'bool'
            }],
            'payable': ![],
            'stateMutability': 'nonpayable',
            'type': 'function'
        }, {
            'constant': ![],
            'inputs': [{
                'internalType': 'address',
                'name': 'from',
                'type': 'address'
            }, {
                'internalType': 'address',
                'name': 'to',
                'type': 'address'
            }, {
                'internalType': 'uint256',
                'name': 'value',
                'type': 'uint256'
            }],
            'name': 'transferFrom',
            'outputs': [{
                'internalType': 'bool',
                'name': '',
                'type': 'bool'
            }],
            'payable': ![],
            'stateMutability': 'nonpayable',
            'type': 'function'
        }]
  },
  'contracts': {
    'usdc': '0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48',
    'dsd': '0xBD2F0Cd039E0BFcf88901C98c0bFAc5ab27566e3',
    'dsds': '0x6Bf977ED1A09214E6209F4EA5f525261f1A2690a',
    'lp': '0x70A87e1b97436D2F194B8B9EBF337bFc7521C70f',
    'uniswap': '0x66e33d2605c5fB25eBb7cd7528E7997b0afA55E8'
  },
	
} 